barony_tranth:
  cities:
    - Belfaux
    - Sofular
  outposts:
    - Orothiar (autonomous Dwarven Enclave)
    - Bloodstone Mine (now home to Svirfneblin allies)

micadonia:
  cities:
    - Dwarvia (Three Kings’ suburb & mine)
